// ============================================================
// main.ts - Core application logic for the License Data Viewer
// ============================================================
// This file handles:
//   1. Fetching license data from a JSON file (converted from Excel)
//   2. Rendering the data in a dynamic HTML table
//   3. Search/filter functionality (by specific column or all columns)
//   4. Sorting functionality (ascending/descending by selected column)
//   5. Pagination (50 rows per page with Previous/Next navigation)
// ============================================================

// --- Type Definition ---
// Define the structure of each license record based on the Excel columns.
// Each property corresponds to a column header in the original spreadsheet.
interface LicenseData {
    "License No": string;
    "Expiration Date": string;
    "First Issuance Date": string;
    "Name": string;
    "Company": string;
    "Address": string;
    "City": string;
    "State": string;
    "Zip Code": string;
    "County": string;
    "BLN - Business License Number": string;
}

// --- State Variables ---
let rawData: LicenseData[] = [];       // Stores the full dataset loaded from JSON
let filteredData: LicenseData[] = [];  // Stores the currently filtered/sorted subset
let currentPage = 1;                   // Tracks the current page for pagination
const rowsPerPage = 50;                // Number of rows displayed per page

// --- DOM Element References ---
// Grab references to key DOM elements once on load to avoid repeated lookups.
const tableBody = document.getElementById('tableBody') as HTMLTableSectionElement;
const searchInput = document.getElementById('searchInput') as HTMLInputElement;
const searchCol = document.getElementById('searchColumn') as HTMLSelectElement;
const sortCol = document.getElementById('sortColumn') as HTMLSelectElement;
const sortOrder = document.getElementById('sortOrder') as HTMLSelectElement;

// --- Data Loading ---
// Fetches the JSON data file from the public directory.
// The data.json file is generated by running `npm run convert` (see convert.js).
async function fetchData() {
    try {
        const response = await fetch('./data.json');
        rawData = await response.json();
        filteredData = [...rawData];

        renderHeader();          // Build table headers from the data keys
        applyFiltersAndSort();   // Initial render with default filters
    } catch (error) {
        console.error("Error loading data:", error);
    }
}

// --- Table Header Rendering ---
// Dynamically creates <th> elements based on the keys of the first data record.
// This makes the table adapt automatically to whatever columns are in the data.
function renderHeader() {
    const headerRow = document.getElementById('headerRow')!;
    if (rawData.length > 0) {
        const columns = Object.keys(rawData[0]);
        headerRow.innerHTML = columns.map(col => `<th>${col}</th>`).join('');
    }
}

// --- Filter & Sort Logic ---
// This is the main function that processes user interactions:
//   1. Filters data based on the search input and selected column
//   2. Sorts the filtered results by the selected sort column and order
//   3. Resets to page 1 and re-renders the table
function applyFiltersAndSort() {
    const searchTerm = searchInput.value.toLowerCase();
    const colToSearch = searchCol.value;
    const colToSort = sortCol.value;
    const order = sortOrder.value;

    // Step 1: Filter — search across all columns or a specific one
    filteredData = rawData.filter(row => {
        if (colToSearch === 'all') {
            // Check every column value for a match
            return Object.values(row).some(val => String(val).toLowerCase().includes(searchTerm));
        } else {
            // Check only the selected column
            return String((row as any)[colToSearch]).toLowerCase().includes(searchTerm);
        }
    });

    // Step 2: Sort — use localeCompare for proper string & numeric sorting
    filteredData.sort((a: any, b: any) => {
        const valA = String(a[colToSort]);
        const valB = String(b[colToSort]);

        // localeCompare with {numeric: true} ensures "10" sorts after "9"
        const compare = valA.localeCompare(valB, undefined, { numeric: true, sensitivity: 'base' });
        return order === 'asc' ? compare : -compare;
    });

    // Reset to the first page whenever filters change
    currentPage = 1;
    updateTable();
}

// --- Table Body Rendering ---
// Renders the current page of data into the table body.
// Also updates the stats counter and pagination info text.
function updateTable() {
    const start = (currentPage - 1) * rowsPerPage;
    const end = start + rowsPerPage;
    const pageData = filteredData.slice(start, end);

    // Build table rows — each cell shows the corresponding value (or empty string if null/undefined)
    tableBody.innerHTML = pageData.map(row => `
        <tr>
            ${Object.values(row).map(v => `<td>${v || ''}</td>`).join('')}
        </tr>
    `).join('');

    // Update the total record count and current page indicator
    document.getElementById('stats')!.innerText = `Total: ${filteredData.length} records`;
    document.getElementById('pageInfo')!.innerText = `Page ${currentPage} of ${Math.ceil(filteredData.length / rowsPerPage) || 1}`;
}

// --- Event Listeners ---
// Attach both 'change' and 'input' events to all control elements.
// 'input' fires on every keystroke (for the search box).
// 'change' fires when a dropdown selection changes.
[searchInput, searchCol, sortCol, sortOrder].forEach(el => {
    el.addEventListener('change', applyFiltersAndSort);
    el.addEventListener('input', applyFiltersAndSort);
});

// --- Pagination Buttons ---
// Previous button: go back one page (if not already on page 1)
document.getElementById('prevBtn')!.onclick = () => {
    if (currentPage > 1) {
        currentPage--;
        updateTable();
    }
};

// Next button: go forward one page (if there are more rows to show)
document.getElementById('nextBtn')!.onclick = () => {
    if (currentPage * rowsPerPage < filteredData.length) {
        currentPage++;
        updateTable();
    }
};

// --- Initialize the App ---
// Kick off data loading when the script runs
fetchData();